# Generated by Django 5.1.7 on 2026-06-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='descuento_tipo',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje (%)'), ('fijo', 'Fijo ($)')], max_length=12, null=True, verbose_name='Tipo de descuento'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='descuento_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de descuento'),
        ),
    ]
