# Generated by Django 5.1.7 on 2026-06-08 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_suscripcion_descuento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
