# Generated by Django 5.1.7 on 2026-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_suscripcion_fecha_inicio_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta_debito', 'Tarjeta de Débito'), ('cortesia', 'Cortesía')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
