# Generated by Django 5.1.7 on 2026-06-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=10, verbose_name='Canal')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enviado_ok', models.BooleanField(default=False, verbose_name='Enviado correctamente')),
                ('respuesta_api', models.TextField(blank=True, default='', verbose_name='Respuesta API')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente', verbose_name='Cliente')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.suscripcion', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-fecha_envio'],
                'unique_together': {('suscripcion', 'canal')},
            },
        ),
    ]
