# Generated by Django 5.1.7 on 2026-06-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('subscriptions', '0004_suscripcion_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognotificacion',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.suscripcion', verbose_name='Suscripción'),
        ),
    ]
