# Generated by Django 5.1.7 on 2026-06-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cliente_foto_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento_identidad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Documento de identidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta_debito', 'Tarjeta de Débito'), ('cortesia', 'Cortesía')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
