# Generated by Django 5.1.7 on 2026-06-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_cliente_documento_identidad_cliente_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='metodo_pago',
        ),
    ]
