# Generated by Django 5.1.7 on 2026-06-09 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_cliente_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena campos personalizados adicionales en formato JSON.', null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dispositivo_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='MAC address debe tener formato XX:XX:XX:XX:XX:XX o XX-XX-XX-XX-XX-XX.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='ID Dispositivo / MAC'),
        ),
    ]
