# Generated by Django 5.1.7 on 2026-06-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_cliente_datos_extra_alter_cliente_dispositivo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto / Text'), ('number', 'Número / Number'), ('boolean', 'Sí/No / Boolean'), ('date', 'Fecha / Date'), ('email', 'Email'), ('select', 'Selección / Select')], default='text', max_length=20, verbose_name='Tipo de campo')),
                ('required', models.BooleanField(default=False, verbose_name='Requerido')),
                ('options', models.TextField(blank=True, help_text='Para tipo "Selección", una opción por línea. / For "Select" type, one option per line.', verbose_name='Opciones')),
                ('vertical', models.CharField(blank=True, choices=[('', '— Global (todas las verticales)'), ('iptv', 'IPTV'), ('gimnasio', 'Gimnasio / Gym'), ('escuela', 'Escuela / School'), ('taller', 'Taller / Workshop'), ('consultorio', 'Consultorio / Clinic'), ('otro', 'Otro / Other')], default='', help_text='Dejar vacío para aplicar a todas las verticales. / Leave empty for all verticals.', max_length=50, verbose_name='Vertical de negocio')),
                ('ordering', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['ordering', 'nombre'],
            },
        ),
    ]
