# Generated by Django 5.1.7 on 2026-06-04 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de perfil'),
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(choices=[('modern', 'Moderno — Azul profundo'), ('corporate', 'Corporativo — Verde elegante'), ('minimal', 'Minimalista — Blanco y negro'), ('vibrant', 'Vibrante — Púrpura neón'), ('dark-neumorphic', 'Dark Neumorphic — Oscuro esmeralda')], default='modern', max_length=30, verbose_name='Tema')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Color secundario')),
                ('bg_color', models.CharField(default='#f1f5f9', max_length=7, verbose_name='Color de fondo')),
                ('text_color', models.CharField(default='#1e293b', max_length=7, verbose_name='Color de texto')),
                ('card_bg', models.CharField(default='#ffffff', max_length=7, verbose_name='Fondo de tarjetas')),
                ('sidebar_bg', models.CharField(default='#111827', max_length=7, verbose_name='Fondo de sidebar')),
                ('button_style', models.CharField(choices=[('rounded', 'Redondeados'), ('square', 'Cuadrados'), ('pill', 'Píldora')], default='rounded', max_length=10, verbose_name='Estilo de botones')),
                ('custom_css', models.TextField(blank=True, default='', verbose_name='CSS personalizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Tema',
                'verbose_name_plural': 'Configuraciones de Tema',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre de usuario')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('view', 'Visualización'), ('other', 'Otro')], max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Objeto')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('details', models.TextField(blank=True, default='', verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='Ruta')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
    ]
