# Generated by Django 5.1.7 on 2026-06-05 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture_themesettings_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del preset')),
                ('icon', models.CharField(choices=[('🎨', '🎨 Paleta'), ('🌈', '🌈 Arcoíris'), ('🎭', '🎭 Teatro'), ('🌟', '🌟 Estrella'), ('🔥', '🔥 Fuego'), ('💎', '💎 Diamante'), ('🌊', '🌊 Ola'), ('🍃', '🍃 Hoja'), ('🌙', '🌙 Luna'), ('☀️', '☀️ Sol'), ('🎯', '🎯 Blanco'), ('💡', '💡 Idea'), ('🚀', '🚀 Cohete'), ('🌸', '🌸 Flor'), ('🌺', '🌺 Hibisco')], default='🎨', max_length=10, verbose_name='Icono')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Color secundario')),
                ('bg_color', models.CharField(default='#f1f5f9', max_length=7, verbose_name='Color de fondo')),
                ('text_color', models.CharField(default='#1e293b', max_length=7, verbose_name='Color de texto')),
                ('card_bg', models.CharField(default='#ffffff', max_length=7, verbose_name='Fondo de tarjetas')),
                ('sidebar_bg', models.CharField(default='#111827', max_length=7, verbose_name='Fondo de sidebar')),
                ('button_style', models.CharField(choices=[('rounded', 'Redondeados'), ('square', 'Cuadrados'), ('pill', 'Píldora')], default='rounded', max_length=10, verbose_name='Estilo de botones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preset Personalizado',
                'verbose_name_plural': 'Presets Personalizados',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
