# Generated by Django 5.1.7 on 2026-06-05 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_custompreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='¡Página no encontrada!', max_length=200, verbose_name='Título')),
                ('message', models.TextField(default='La página que buscas no existe o fue movida. Usa la navegación para encontrar lo que necesitas.', verbose_name='Mensaje')),
                ('show_pixel_art', models.BooleanField(default=True, verbose_name='Mostrar arte pixelado')),
                ('bg_color', models.CharField(default='#1a202c', max_length=7, verbose_name='Color de fondo')),
                ('text_color', models.CharField(default='#e2e8f0', max_length=7, verbose_name='Color de texto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de página 404',
                'verbose_name_plural': 'Configuración de página 404',
            },
        ),
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_minutes', models.PositiveIntegerField(default=60, verbose_name='Tiempo de sesión (minutos)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de sesión',
                'verbose_name_plural': 'Configuración de sesión',
            },
        ),
    ]
