# Generated by Django 5.1.7 on 2026-06-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_errorpagesettings_sessionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='pixel_bg',
            field=models.CharField(choices=[('none', 'Ninguno'), ('stars', 'Estrellas'), ('grid', 'Cuadrícula'), ('checker', 'Ajedrez'), ('circuit', 'Circuitos'), ('diamond', 'Diamantes'), ('rain', 'Lluvia'), ('mountain', 'Montañas'), ('nebula', 'Nebulosa'), ('matrix', 'Matrix')], default='none', max_length=20, verbose_name='Fondo pixel art'),
        ),
    ]
