# Generated by Django 5.1.7 on 2026-06-08 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_themesettings_pixel_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('categoria', models.CharField(choices=[('general', 'General'), ('clientes', 'Clientes'), ('finanzas', 'Finanzas'), ('suscripciones', 'Suscripciones'), ('sistema', 'Sistema'), ('otro', 'Otro')], default='general', max_length=20, verbose_name='Categoría')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['completada', '-prioridad', '-created_at'],
            },
        ),
    ]
