# Generated by Django 5.1.7 on 2026-06-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorpagesettings',
            options={'verbose_name': 'Configuración de páginas de error', 'verbose_name_plural': 'Configuración de páginas de error'},
        ),
        migrations.AddField(
            model_name='errorpagesettings',
            name='bg_color_500',
            field=models.CharField(default='#1a202c', max_length=7, verbose_name='Color de fondo (500)'),
        ),
        migrations.AddField(
            model_name='errorpagesettings',
            name='message_500',
            field=models.TextField(default='Ocurrió un error inesperado. El equipo técnico ha sido notificado. Intenta de nuevo más tarde.', verbose_name='Mensaje (500)'),
        ),
        migrations.AddField(
            model_name='errorpagesettings',
            name='show_pixel_art_500',
            field=models.BooleanField(default=True, verbose_name='Mostrar arte pixelado (500)'),
        ),
        migrations.AddField(
            model_name='errorpagesettings',
            name='text_color_500',
            field=models.CharField(default='#e2e8f0', max_length=7, verbose_name='Color de texto (500)'),
        ),
        migrations.AddField(
            model_name='errorpagesettings',
            name='title_500',
            field=models.CharField(default='¡Error interno del servidor!', max_length=200, verbose_name='Título (500)'),
        ),
    ]
