# Generated by Django 5.1.7 on 2026-06-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_errorpagesettings_500_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='text_border_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Color del borde de texto'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_border_width',
            field=models.PositiveIntegerField(default=0, verbose_name='Grosor del borde de texto'),
        ),
    ]
