# Generated by Django 5.1.7 on 2026-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_themesettings_text_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='text_bold',
            field=models.BooleanField(default=False, verbose_name='Negrilla'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_italic',
            field=models.BooleanField(default=False, verbose_name='Itálica'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_strikethrough',
            field=models.BooleanField(default=False, verbose_name='Tachado'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_underline',
            field=models.BooleanField(default=False, verbose_name='Subrayado'),
        ),
    ]
