# Generated by Django 5.1.7 on 2026-06-08 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_themesettings_text_style_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('mensaje', models.TextField(help_text='Placeholders disponibles: {cliente}, {plan}, {vencimiento}, {precio}', verbose_name='Mensaje')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de recordatorio',
                'verbose_name_plural': 'Plantillas de recordatorio',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='Código QR')),
                ('session_status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado')], default='disconnected', max_length=20, verbose_name='Estado de sesión')),
                ('last_qr_at', models.DateTimeField(blank=True, null=True, verbose_name='Último QR generado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de WhatsApp',
                'verbose_name_plural': 'Configuración de WhatsApp',
            },
        ),
    ]
