# Generated by Django 5.1.7 on 2026-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_recordatoriotemplate_whatsappconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatoriotemplate',
            name='categoria',
            field=models.CharField(choices=[('vencimiento', 'Recordatorio de vencimiento'), ('bienvenida', 'Bienvenida / Asignación'), ('oferta', 'Oferta / Promoción'), ('personalizado', 'Personalizado')], default='personalizado', max_length=20, verbose_name='Categoría'),
        ),
    ]
