# Generated by Django 5.1.7 on 2026-06-10 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_errorreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen para el fondo de la página de inicio. Se recomienda 1920x1080px.', null=True, upload_to='landing_bg/', verbose_name='Imagen de fondo')),
                ('gradient_from', models.CharField(default='#111827', help_text='Color inicial del degradado (formato hex, rgb, o Tailwind: gray-900/95)', max_length=50, verbose_name='Degradado inicial')),
                ('gradient_to', models.CharField(default='#1e3a5f', help_text='Color final del degradado (formato hex, rgb, o Tailwind: blue-900/90)', max_length=50, verbose_name='Degradado final')),
                ('overlay_opacity', models.IntegerField(default=85, help_text='Opacidad del degradado superpuesto (0-100)', verbose_name='Opacidad de la capa')),
                ('show_stats', models.BooleanField(default=True, verbose_name='Mostrar estadísticas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de página de inicio',
                'verbose_name_plural': 'Configuración de página de inicio',
            },
        ),
    ]
