# Generated by Django 5.1.7 on 2026-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_landingpageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='pixel_bg',
            field=models.CharField(choices=[('none', 'Ninguno'), ('stars', 'Estrellas'), ('grid', 'Cuadrícula'), ('checker', 'Ajedrez'), ('circuit', 'Circuitos'), ('diamond', 'Diamantes'), ('rain', 'Lluvia'), ('mountain', 'Montañas'), ('nebula', 'Nebulosa'), ('matrix', 'Matrix'), ('cyberpunk', 'Cyberpunk — Neón'), ('aurora', 'Aurora Boreal'), ('galaxy', 'Galaxia'), ('sakura', 'Cerezos / Sakura'), ('neon', 'Neón'), ('ocean', 'Océano'), ('lava', 'Lava'), ('city', 'Ciudad Nocturna'), ('forest', 'Bosque')], default='none', max_length=20, verbose_name='Fondo pixel art'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='pixel_bg',
            field=models.CharField(choices=[('none', 'Ninguno'), ('stars', 'Estrellas'), ('grid', 'Cuadrícula'), ('checker', 'Ajedrez'), ('circuit', 'Circuitos'), ('diamond', 'Diamantes'), ('rain', 'Lluvia'), ('mountain', 'Montañas'), ('nebula', 'Nebulosa'), ('matrix', 'Matrix'), ('cyberpunk', 'Cyberpunk — Neón'), ('aurora', 'Aurora Boreal'), ('galaxy', 'Galaxia'), ('sakura', 'Cerezos / Sakura'), ('neon', 'Neón'), ('ocean', 'Océano'), ('lava', 'Lava'), ('city', 'Ciudad Nocturna'), ('forest', 'Bosque')], default='none', max_length=20, verbose_name='Fondo pixel art'),
        ),
    ]
