# Generated by Django 5.1.7 on 2026-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_landingpageconfig_pixel_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='error_traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback del error'),
        ),
    ]
