# Generated by Django 5.1.7 on 2026-06-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.suscripcion', verbose_name='Suscripción relacionada')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha'],
            },
        ),
    ]
