from .models import ThemeSettings, SessionConfig

_TRANSLATIONS = {
    'es': {
        'dashboard': 'Dashboard',
        'clientes': 'Clientes',
        'suscripciones': 'Suscripciones',
        'finanzas': 'Finanzas',
        'notificaciones': 'Notificaciones',
        'actividad': 'Actividad',
        'admin_django': 'Admin Django',
        'mi_perfil': 'Mi Perfil',
        'reportes': 'Reportes',
        'personalizar_tema': 'Personalizar Tema',
        'personalizar_404': 'Personalizar 404',
        'tiempo_de_sesion': 'Tiempo de sesión',
        'documentacion': 'Documentación',
        'acerca_de_uso': 'Acerca de / Uso',
        'modo_oscuro': 'Modo oscuro',
        'cerrar_sesion': 'Cerrar sesión',
        'tu_sesion_esta_por_expirar': 'Tu sesión está por expirar',
        'extender_sesion': 'Extender sesión',
        'estas_seguro': '¿Estás seguro?',
        'esta_accion_no_se_puede_deshacer': 'Esta acción no se puede deshacer.',
        'cancelar': 'Cancelar',
        'eliminar': 'Eliminar',
        'bienvenido': '¡Bienvenido, %s!',
        'sin_grupo_asignado': 'Sin grupo asignado',
        'admin_maestro': 'Admin Maestro',
        'miembro_desde': 'Miembro desde:',
        'ultimo_acceso': 'Último acceso:',
        'primera_vez': 'Primera vez',
        'sin_email': 'Sin email',
        'editar_perfil': 'Editar perfil',
        'clientes_activos': 'Clientes Activos',
        'suscripciones_activas': 'Suscripciones Activas',
        'por_vencer': 'Por Vencer (3 días)',
        'vencidas': 'Vencidas',
        'saldo_del_mes': 'Saldo del Mes',
        'ingresos_vs_egresos': 'Ingresos vs Egresos (6 meses)',
        'distribucion_por_plan': 'Distribución por Plan',
        'suscripciones_temporales': 'Suscripciones Temporales',
        'ingresos_este_mes': 'Ingresos este mes:',
        'egresos_este_mes': 'Egresos este mes:',
        'suscripciones_activas_label': 'Suscripciones activas:',
        'por_vencer_proximamente': 'Por vencer próximamente:',
        'vencidas_label': 'Vencidas:',
        'ultimos_movimientos': 'Últimos Movimientos',
        'ultimos_clientes': 'Últimos Clientes',
        'ir_al_inicio': 'Ir al inicio',
        'iniciar_sesion': 'Iniciar sesión',
        'ayuda': 'Ayuda',
        'personalizar_pagina_404': 'Personalizar página 404',
        'config_404_desc': 'Configura cómo se ve la página cuando alguien visita una URL que no existe.',
        'titulo': 'Título',
        'mensaje': 'Mensaje',
        'mostrar_arte_pixelado': 'Mostrar arte pixelado (castillo y estrellas)',
        'guardar': 'Guardar',
        'volver': 'Volver',
        'vista_previa': 'Vista previa',
        'configuracion_de_sesion': 'Configuración de sesión',
        'config_sesion_desc': 'Configura cada cuánto tiempo se cierra la sesión automáticamente por inactividad.',
        'guardar_cambios': 'Guardar cambios',
        'cambiar_contraseña': 'Cambiar contraseña',
        'recortar_foto': 'Recortar foto',
        'iniciar_sesion_title': 'Iniciar Sesión',
        'usuario': 'Usuario',
        'contraseña': 'Contraseña',
        'credenciales_incorrectas': 'Usuario o contraseña incorrectos.',
        'entrar': 'Entrar',
        'neto_mensual': 'Neto Mensual',
        'prediccion_de_gananciasperdidas': 'Predicción de Ganancias/Pérdidas',
        'basado_en_regresion_lineal_simple_sobre_los_ultimos_6_meses': 'Basado en regresión lineal simple sobre los últimos 6 meses',
        'resumen_ejecutivo': 'Resumen Ejecutivo',
        'neto_del_mes': 'Neto del mes:',
        'clientes_activos_label': 'Clientes activos:',
        'tipo': 'Tipo',
        'monto': 'Monto',
        'fecha': 'Fecha',
        'descripcion': 'Descripción',
        'sin_movimientos': 'Sin movimientos',
        'nombre': 'Nombre',
        'telefono': 'Teléfono',
        'registro': 'Registro',
        'sin_clientes': 'Sin clientes',
        'como_usar_el_sistema': 'Cómo usar el sistema',
        'como_usar_iptv_manager': 'Cómo usar IPTV Manager',
        'guia_paso_a_paso_para_operar_el_sistema': 'Guía paso a paso para operar el sistema.',
        'primeros_pasos': 'Primeros pasos',
        'gestion_de_clientes': 'Gestión de Clientes',
        'suscripciones_y_planes': 'Suscripciones y Planes',
        'personalizacion': 'Personalización',
        'roles_y_permisos': 'Roles y Permisos',
        'solucion_de_problemas': 'Solución de problemas',
        'generar_reporte': 'Generar Reporte',
        'selecciona_las_secciones_el_formato_y_el_diseno_para_tu_reporte': 'Selecciona las secciones, el formato y el diseño para tu reporte.',
        'secciones': 'Secciones',
        'periodo_opcional': 'Período (opcional)',
        'desde': 'Desde',
        'hasta': 'Hasta',
        'formato_y_diseno': 'Formato y Diseño',
        'formato_de_salida': 'Formato de salida',
        'plantilla_pdf': 'Plantilla PDF',
        'pdf': 'PDF',
        'excel': 'Excel',
        'jpg_vista_previa': 'JPG (Vista Previa)',
        'ajustes_pdf': 'Ajustes PDF',
        'margenes': 'Márgenes',
        'pequenos_15_cm': 'Pequeños (1.5 cm)',
        'normales_254_cm': 'Normales (2.54 cm)',
        'grandes_30_cm': 'Grandes (3.0 cm)',
        'tipografia': 'Tipografía',
        'helvetica_arial': 'Helvetica (Arial)',
        'times_roman': 'Times Roman',
        'courier': 'Courier',
        'espaciado': 'Espaciado',
        'compacto': 'Compacto',
        'normal': 'Normal',
        'espacioso': 'Espacioso',
        'tipo_de_grafico': 'Tipo de gráfico',
        'barras': 'Barras',
        'pastel_pie': 'Pastel (Pie)',
        'orientacion_horizontal_landscape': 'Orientación horizontal (Landscape)',
        'descargar': 'Descargar',
        'atras': 'Atrás',
        'expira_en': 'Expira en ',
        'tus_presets_guardados': 'Tus presets guardados',
        'selecciona_un_preset_para_sobrescribir_los_colores': 'Selecciona un preset para sobrescribir los colores.',
        'guardar_como_preset': 'Guardar como preset',
        'guardar_preset_personalizado': 'Guardar preset personalizado',
        'nombre_del_preset': 'Nombre del preset',
        'mi_preset': 'Mi preset',
        'icono': 'Icono',
        'aplicar_preset': '¿Aplicar preset?',
        'se_sobrescribiran_los_colores_actuales_con_los_del_preset_guardado': 'Se sobrescribirán los colores actuales con los del preset guardado.',
        'se_eliminara_permanentemente': 'Este preset guardado se eliminará permanentemente.',
        'haz_clic_para_seleccionar_podras_recortar_la_imagen_antes_de_guardar': 'Haz clic para seleccionar. Podrás recortar la imagen antes de guardar.',
        'aplicar_recorte': 'Aplicar recorte',
        'cambiar_contrasena': 'Cambiar Contraseña',
        'registro_de_actividad': 'Registro de Actividad',
        'registro_de_actividad_del_sistema': 'Registro de Actividad del Sistema',
        'seleccionar_todos': 'Seleccionar todos',
        'eliminar_seleccionados': 'Eliminar seleccionados',
        'accion': 'Acción',
        'modelo': 'Modelo',
        'objeto': 'Objeto',
        'ip': 'IP',
        'no_hay_registros_de_actividad': 'No hay registros de actividad.',
        'nuevo_cliente': '+ Nuevo Cliente',
        'buscar_por_nombre_telefono_o_mac': 'Buscar por nombre, teléfono o MAC...',
        'dispositivo': 'Dispositivo',
        'acciones': 'Acciones',
        'ver': 'Ver',
        'editar': 'Editar',
        'no_hay_clientes_registrados': 'No hay clientes registrados',
        'anterior': 'Anterior',
        'siguiente': 'Siguiente',
        'datos': 'Datos',
        'activo': 'Activo',
        'si': 'Sí',
        'no': 'No',
        'nueva': '+ Nueva',
        'plan': 'Plan',
        'inicio': 'Inicio',
        'vencimiento': 'Vencimiento',
        'estado': 'Estado',
        'recordatorio': 'Recordatorio',
        'sin_suscripciones': 'Sin suscripciones',
        'anotaciones': 'Anotaciones',
        'nueva_anotacion': 'Nueva anotación...',
        'agregar': 'Agregar',
        'sin_anotaciones': 'Sin anotaciones',
        'historial': 'Historial',
        'agregar_nota_al_historial': 'Agregar nota al historial...',
        'sin_historial': 'Sin historial',
        'desactivar_cliente': 'Desactivar Cliente',
        'desactivar': 'Desactivar',
        'si_desactivar': 'Sí, desactivar',
        'todos_los_estados': 'Todos los estados',
        'cancelado': 'Cancelado',
        'renovar': 'Renovar',
        'no_hay_suscripciones': 'No hay suscripciones',
        'nueva_suscripcion': '+ Nueva Suscripción',
        'nuevo_movimiento': '+ Nuevo Movimiento',
        'movimientos_financieros': 'Movimientos Financieros',
        'todos': 'Todos',
        'ingresos': 'Ingresos',
        'egresos': 'Egresos',
        'sin_movimientos_financieros': 'Sin movimientos',
        'registrar_movimiento': 'Registrar Movimiento',
        'log_de_notificaciones': 'Log de Notificaciones',
        'canal': 'Canal',
        'destinatario': 'Destinatario',
        'enviado': '✓ Enviado',
        'fallo': '✗ Falló',
        'sin_notificaciones': 'Sin notificaciones',
        'bloqueado': 'Bloqueado',
        'cuenta_bloqueada': 'Cuenta Bloqueada',
        'demasiados_intentos_fallidos_intenta_de_nuevo_mas_tarde': 'Demostrados intentos fallidos. Intenta de nuevo más tarde.',
        'volver_al_login': 'Volver al login',
        'sistema_de_gestion_de_servicios_iptv': 'Sistema de Gestión de Servicios IPTV',
        'iptv_manager_es_un_sistema_integral': 'IPTV Manager es un sistema integral para la administración de pequeñas y medianas empresas proveedoras de servicios IPTV.',
        'clientes_activos_estadistica': 'Clientes activos',
        'suscripciones_activas_estadistica': 'Suscripciones activas',
        'planes_disponibles': 'Planes disponibles',
        'acerca_de': 'Acerca de',
        'gestiona_clientes_asigna_suscripciones_controla_finanzas_y_automatiza_recordatorios': 'Gestiona clientes, asigna suscripciones, controla finanzas y automatiza recordatorios — todo desde un solo lugar.',
        'fondo_pixel_art': 'Fondo pixel art',
        'ninguno': 'Ninguno',
        'estrellas': 'Estrellas',
        'cuadricula': 'Cuadrícula',
        'ajedrez': 'Ajedrez',
        'circuitos': 'Circuitos',
        'diamantes': 'Diamantes',
        'lluvia': 'Lluvia',
        'montanas': 'Montañas',
        'nebulosa': 'Nebulosa',
        'matrix': 'Matrix',
        'total_cliente': 'Total clientes:',
        'subs_act': 'Subs Act.',
        'total_gastado': 'Total Gastado',
    },
    'en': {
        'dashboard': 'Dashboard',
        'clientes': 'Clients',
        'suscripciones': 'Subscriptions',
        'finanzas': 'Finance',
        'notificaciones': 'Notifications',
        'actividad': 'Activity',
        'admin_django': 'Django Admin',
        'mi_perfil': 'My Profile',
        'reportes': 'Reports',
        'personalizar_tema': 'Customize Theme',
        'personalizar_404': 'Customize 404',
        'tiempo_de_sesion': 'Session Time',
        'documentacion': 'Documentation',
        'acerca_de_uso': 'About / Usage',
        'modo_oscuro': 'Dark mode',
        'cerrar_sesion': 'Sign out',
        'tu_sesion_esta_por_expirar': 'Your session is about to expire',
        'extender_sesion': 'Extend session',
        'estas_seguro': 'Are you sure?',
        'esta_accion_no_se_puede_deshacer': 'This action cannot be undone.',
        'cancelar': 'Cancel',
        'eliminar': 'Delete',
        'bienvenido': 'Welcome, %s!',
        'sin_grupo_asignado': 'No group assigned',
        'admin_maestro': 'Master Admin',
        'miembro_desde': 'Member since:',
        'ultimo_acceso': 'Last login:',
        'primera_vez': 'First time',
        'sin_email': 'No email',
        'editar_perfil': 'Edit profile',
        'clientes_activos': 'Active Clients',
        'suscripciones_activas': 'Active Subscriptions',
        'por_vencer': 'Expiring Soon (3 days)',
        'vencidas': 'Expired',
        'saldo_del_mes': 'Month Balance',
        'ingresos_vs_egresos': 'Income vs Expenses (6 months)',
        'distribucion_por_plan': 'Distribution by Plan',
        'suscripciones_temporales': 'Temporal Subscriptions',
        'ingresos_este_mes': 'Income this month:',
        'egresos_este_mes': 'Expenses this month:',
        'suscripciones_activas_label': 'Active subscriptions:',
        'por_vencer_proximamente': 'Expiring soon:',
        'vencidas_label': 'Expired:',
        'ultimos_movimientos': 'Latest Transactions',
        'ultimos_clientes': 'Latest Clients',
        'ir_al_inicio': 'Go to home',
        'iniciar_sesion': 'Sign in',
        'ayuda': 'Help',
        'personalizar_pagina_404': 'Customize 404 page',
        'config_404_desc': 'Configure how the page looks when someone visits a URL that doesn\'t exist.',
        'titulo': 'Title',
        'mensaje': 'Message',
        'mostrar_arte_pixelado': 'Show pixel art (castle and stars)',
        'guardar': 'Save',
        'volver': 'Go back',
        'vista_previa': 'Preview',
        'configuracion_de_sesion': 'Session Configuration',
        'config_sesion_desc': 'Set how often the session automatically expires due to inactivity.',
        'guardar_cambios': 'Save changes',
        'cambiar_contraseña': 'Change password',
        'recortar_foto': 'Crop photo',
        'iniciar_sesion_title': 'Sign In',
        'usuario': 'Username',
        'contraseña': 'Password',
        'credenciales_incorrectas': 'Invalid username or password.',
        'entrar': 'Sign in',
        'neto_mensual': 'Monthly Net',
        'prediccion_de_gananciasperdidas': 'Profit/Loss Prediction',
        'basado_en_regresion_lineal_simple_sobre_los_ultimos_6_meses': 'Based on simple linear regression over the last 6 months',
        'resumen_ejecutivo': 'Executive Summary',
        'neto_del_mes': 'Month net:',
        'clientes_activos_label': 'Active clients:',
        'tipo': 'Type',
        'monto': 'Amount',
        'fecha': 'Date',
        'descripcion': 'Description',
        'sin_movimientos': 'No transactions',
        'nombre': 'Name',
        'telefono': 'Phone',
        'registro': 'Registered',
        'sin_clientes': 'No clients',
        'como_usar_el_sistema': 'How to use the system',
        'como_usar_iptv_manager': 'How to use IPTV Manager',
        'guia_paso_a_paso_para_operar_el_sistema': 'Step-by-step guide to operate the system.',
        'primeros_pasos': 'First steps',
        'gestion_de_clientes': 'Client Management',
        'suscripciones_y_planes': 'Subscriptions & Plans',
        'personalizacion': 'Customization',
        'roles_y_permisos': 'Roles & Permissions',
        'solucion_de_problemas': 'Troubleshooting',
        'generar_reporte': 'Generate Report',
        'selecciona_las_secciones_el_formato_y_el_diseno_para_tu_reporte': 'Select sections, format and design for your report.',
        'secciones': 'Sections',
        'periodo_opcional': 'Period (optional)',
        'desde': 'From',
        'hasta': 'To',
        'formato_y_diseno': 'Format & Design',
        'formato_de_salida': 'Output format',
        'plantilla_pdf': 'PDF Template',
        'pdf': 'PDF',
        'excel': 'Excel',
        'jpg_vista_previa': 'JPG (Preview)',
        'ajustes_pdf': 'PDF Settings',
        'margenes': 'Margins',
        'pequenos_15_cm': 'Small (1.5 cm)',
        'normales_254_cm': 'Normal (2.54 cm)',
        'grandes_30_cm': 'Large (3.0 cm)',
        'tipografia': 'Font',
        'helvetica_arial': 'Helvetica (Arial)',
        'times_roman': 'Times Roman',
        'courier': 'Courier',
        'espaciado': 'Spacing',
        'compacto': 'Compact',
        'normal': 'Normal',
        'espacioso': 'Spacious',
        'tipo_de_grafico': 'Chart type',
        'barras': 'Bar',
        'pastel_pie': 'Pie',
        'orientacion_horizontal_landscape': 'Landscape orientation',
        'descargar': 'Download',
        'atras': 'Back',
        'expira_en': 'Expires in ',
        'tus_presets_guardados': 'Your saved presets',
        'selecciona_un_preset_para_sobrescribir_los_colores': 'Select a preset to overwrite colors.',
        'guardar_como_preset': 'Save as preset',
        'guardar_preset_personalizado': 'Save custom preset',
        'nombre_del_preset': 'Preset name',
        'mi_preset': 'My preset',
        'icono': 'Icon',
        'aplicar_preset': 'Apply preset?',
        'se_sobrescribiran_los_colores_actuales_con_los_del_preset_guardado': 'Current colors will be overwritten with the saved preset.',
        'se_eliminara_permanentemente': 'This saved preset will be permanently deleted.',
        'haz_clic_para_seleccionar_podras_recortar_la_imagen_antes_de_guardar': 'Click to select. You can crop the image before saving.',
        'aplicar_recorte': 'Apply crop',
        'cambiar_contrasena': 'Change Password',
        'registro_de_actividad': 'Activity Log',
        'registro_de_actividad_del_sistema': 'System Activity Log',
        'seleccionar_todos': 'Select all',
        'eliminar_seleccionados': 'Delete selected',
        'accion': 'Action',
        'modelo': 'Model',
        'objeto': 'Object',
        'ip': 'IP',
        'no_hay_registros_de_actividad': 'No activity records.',
        'nuevo_cliente': '+ New Client',
        'buscar_por_nombre_telefono_o_mac': 'Search by name, phone or MAC...',
        'dispositivo': 'Device',
        'acciones': 'Actions',
        'ver': 'View',
        'editar': 'Edit',
        'no_hay_clientes_registrados': 'No registered clients',
        'anterior': 'Previous',
        'siguiente': 'Next',
        'datos': 'Data',
        'activo': 'Active',
        'si': 'Yes',
        'no': 'No',
        'nueva': '+ New',
        'plan': 'Plan',
        'inicio': 'Start',
        'vencimiento': 'Expiry',
        'estado': 'Status',
        'recordatorio': 'Reminder',
        'sin_suscripciones': 'No subscriptions',
        'anotaciones': 'Notes',
        'nueva_anotacion': 'New note...',
        'agregar': 'Add',
        'sin_anotaciones': 'No notes',
        'historial': 'History',
        'agregar_nota_al_historial': 'Add note to history...',
        'sin_historial': 'No history',
        'desactivar_cliente': 'Deactivate Client',
        'desactivar': 'Deactivate',
        'si_desactivar': 'Yes, deactivate',
        'todos_los_estados': 'All statuses',
        'cancelado': 'Canceled',
        'renovar': 'Renew',
        'no_hay_suscripciones': 'No subscriptions',
        'nueva_suscripcion': '+ New Subscription',
        'nuevo_movimiento': '+ New Transaction',
        'movimientos_financieros': 'Financial Transactions',
        'todos': 'All',
        'ingresos': 'Income',
        'egresos': 'Expenses',
        'sin_movimientos_financieros': 'No transactions',
        'registrar_movimiento': 'Register Transaction',
        'log_de_notificaciones': 'Notification Log',
        'canal': 'Channel',
        'destinatario': 'Recipient',
        'enviado': '✓ Sent',
        'fallo': '✗ Failed',
        'sin_notificaciones': 'No notifications',
        'bloqueado': 'Locked',
        'cuenta_bloqueada': 'Account Locked',
        'demasiados_intentos_fallidos_intenta_de_nuevo_mas_tarde': 'Too many failed attempts. Try again later.',
        'volver_al_login': 'Back to login',
        'sistema_de_gestion_de_servicios_iptv': 'IPTV Service Management System',
        'iptv_manager_es_un_sistema_integral': 'IPTV Manager is a comprehensive system for managing small and medium IPTV service providers.',
        'clientes_activos_estadistica': 'Active Clients',
        'suscripciones_activas_estadistica': 'Active Subscriptions',
        'planes_disponibles': 'Available Plans',
        'acerca_de': 'About',
        'gestiona_clientes_asigna_suscripciones_controla_finanzas_y_automatiza_recordatorios': 'Manage clients, assign subscriptions, control finances and automate reminders — all from one place.',
        'fondo_pixel_art': 'Pixel art background',
        'ninguno': 'None',
        'estrellas': 'Stars',
        'cuadricula': 'Grid',
        'ajedrez': 'Checkerboard',
        'circuitos': 'Circuits',
        'diamantes': 'Diamonds',
        'lluvia': 'Rain',
        'montanas': 'Mountains',
        'nebulosa': 'Nebula',
        'matrix': 'Matrix',
        'total_cliente': 'Total clients:',
        'subs_act': 'Active Subs',
        'total_gastado': 'Total Spent',
    },
}


def theme_context(request):
    ctx = {
        'theme_primary': '#2563eb',
        'theme_secondary': '#1d4ed8',
        'theme_bg': '#f1f5f9',
        'theme_text': '#1e293b',
        'theme_card_bg': '#ffffff',
        'theme_sidebar_bg': '#111827',
        'theme_radius': '0.5rem',
        'theme_custom_css': '',
        'theme_pixel_bg': 'none',
        'session_timeout_minutes': 60,
    }
    if request.user.is_authenticated:
        try:
            theme = request.user.theme
            ctx.update({
                'theme_primary': theme.primary_color,
                'theme_secondary': theme.secondary_color,
                'theme_bg': theme.bg_color,
                'theme_text': theme.text_color,
                'theme_card_bg': theme.card_bg,
                'theme_sidebar_bg': theme.sidebar_bg,
                'theme_radius': '9999px' if theme.button_style == 'pill' else ('0.125rem' if theme.button_style == 'square' else '0.5rem'),
                'theme_custom_css': theme.custom_css or '',
                'theme_pixel_bg': theme.pixel_bg or 'none',
            })
        except ThemeSettings.DoesNotExist:
            pass
        try:
            cfg = SessionConfig.get_config()
            ctx['session_timeout_minutes'] = cfg.timeout_minutes
        except Exception:
            pass

    lang = getattr(request, 'session', None) and request.session.get('django_language', None) or 'es'
    if lang not in _TRANSLATIONS:
        lang = 'es'
    ctx['LANG'] = lang
    ctx['LANGUAGE_CODE'] = lang
    ctx['tr'] = _TRANSLATIONS[lang]

    return ctx
