from .models import ThemeSettings, SessionConfig

_TRANSLATIONS = {
    'es': {
        'dashboard': 'Dashboard',
        'clientes': 'Clientes',
        'suscripciones': 'Suscripciones',
        'finanzas': 'Finanzas',
        'notificaciones': 'Notificaciones',
        'actividad': 'Actividad',
        'admin_django': 'Admin Django',
        'mi_perfil': 'Mi Perfil',
        'reportes': 'Reportes',
        'personalizar_tema': 'Personalizar Tema',
        'personalizar_404': 'Personalizar 404',
        'tiempo_de_sesion': 'Tiempo de sesión',
        'documentacion': 'Documentación',
        'acerca_de_uso': 'Acerca de / Uso',
        'modo_oscuro': 'Modo oscuro',
        'cerrar_sesion': 'Cerrar sesión',
        'tu_sesion_esta_por_expirar': 'Tu sesión está por expirar',
        'extender_sesion': 'Extender sesión',
        'estas_seguro': '¿Estás seguro?',
        'esta_accion_no_se_puede_deshacer': 'Esta acción no se puede deshacer.',
        'cancelar': 'Cancelar',
        'eliminar': 'Eliminar',
        'bienvenido': '¡Bienvenido, %s!',
        'sin_grupo_asignado': 'Sin grupo asignado',
        'admin_maestro': 'Admin Maestro',
        'miembro_desde': 'Miembro desde:',
        'ultimo_acceso': 'Último acceso:',
        'primera_vez': 'Primera vez',
        'sin_email': 'Sin email',
        'editar_perfil': 'Editar perfil',
        'clientes_activos': 'Clientes Activos',
        'suscripciones_activas': 'Suscripciones Activas',
        'por_vencer': 'Por Vencer (3 días)',
        'vencidas': 'Vencidas',
        'saldo_del_mes': 'Saldo del Mes',
        'ingresos_vs_egresos': 'Ingresos vs Egresos (6 meses)',
        'distribucion_por_plan': 'Distribución por Plan',
        'suscripciones_temporales': 'Suscripciones Temporales',
        'ingresos_este_mes': 'Ingresos este mes:',
        'egresos_este_mes': 'Egresos este mes:',
        'suscripciones_activas_label': 'Suscripciones activas:',
        'por_vencer_proximamente': 'Por vencer próximamente:',
        'vencidas_label': 'Vencidas:',
        'ultimos_movimientos': 'Últimos Movimientos',
        'ultimos_clientes': 'Últimos Clientes',
        'ir_al_inicio': 'Ir al inicio',
        'iniciar_sesion': 'Iniciar sesión',
        'ayuda': 'Ayuda',
        'personalizar_pagina_404': 'Personalizar página 404',
        'config_404_desc': 'Configura cómo se ve la página cuando alguien visita una URL que no existe.',
        'titulo': 'Título',
        'mensaje': 'Mensaje',
        'mostrar_arte_pixelado': 'Mostrar arte pixelado (castillo y estrellas)',
        'guardar': 'Guardar',
        'volver': 'Volver',
        'vista_previa': 'Vista previa',
        'configuracion_de_sesion': 'Configuración de sesión',
        'config_sesion_desc': 'Configura cada cuánto tiempo se cierra la sesión automáticamente por inactividad.',
        'guardar_cambios': 'Guardar cambios',
        'cambiar_contraseña': 'Cambiar contraseña',
        'recortar_foto': 'Recortar foto',
        'iniciar_sesion_title': 'Iniciar Sesión',
        'usuario': 'Usuario',
        'contraseña': 'Contraseña',
        'credenciales_incorrectas': 'Usuario o contraseña incorrectos.',
        'entrar': 'Entrar',
        'neto_mensual': 'Neto Mensual',
        'prediccion_de_gananciasperdidas': 'Predicción de Ganancias/Pérdidas',
        'basado_en_regresion_lineal_simple_sobre_los_ultimos_6_meses': 'Basado en regresión lineal simple sobre los últimos 6 meses',
        'resumen_ejecutivo': 'Resumen Ejecutivo',
        'neto_del_mes': 'Neto del mes:',
        'clientes_activos_label': 'Clientes activos:',
        'tipo': 'Tipo',
        'monto': 'Monto',
        'fecha': 'Fecha',
        'descripcion': 'Descripción',
        'sin_movimientos': 'Sin movimientos',
        'nombre': 'Nombre',
        'telefono': 'Teléfono',
        'registro': 'Registro',
        'sin_clientes': 'Sin clientes',
        'documento_identidad': 'Documento de identidad',
        'metodo_pago': 'Método de pago',
        'efectivo': 'Efectivo',
        'cheque': 'Cheque',
        'tarjeta_debito': 'Tarjeta de Débito',
        'cortesia': 'Cortesía',
        'como_usar_el_sistema': 'Cómo usar el sistema',
        'como_usar_iptv_manager': 'Cómo usar IPTV Manager',
        'guia_paso_a_paso_para_operar_el_sistema': 'Guía paso a paso para operar el sistema.',
        'primeros_pasos': 'Primeros pasos',
        'gestion_de_clientes': 'Gestión de Clientes',
        'suscripciones_y_planes': 'Suscripciones y Planes',
        'personalizacion': 'Personalización',
        'roles_y_permisos': 'Roles y Permisos',
        'solucion_de_problemas': 'Solución de problemas',
        'generar_reporte': 'Generar Reporte',
        'selecciona_las_secciones_el_formato_y_el_diseno_para_tu_reporte': 'Selecciona las secciones, el formato y el diseño para tu reporte.',
        'secciones': 'Secciones',
        'periodo_opcional': 'Período (opcional)',
        'desde': 'Desde',
        'hasta': 'Hasta',
        'formato_y_diseno': 'Formato y Diseño',
        'formato_de_salida': 'Formato de salida',
        'plantilla_pdf': 'Plantilla PDF',
        'pdf': 'PDF',
        'excel': 'Excel',
        'jpg_vista_previa': 'JPG (Vista Previa)',
        'ajustes_pdf': 'Ajustes PDF',
        'margenes': 'Márgenes',
        'pequenos_15_cm': 'Pequeños (1.5 cm)',
        'normales_254_cm': 'Normales (2.54 cm)',
        'grandes_30_cm': 'Grandes (3.0 cm)',
        'tipografia': 'Tipografía',
        'helvetica_arial': 'Helvetica (Arial)',
        'times_roman': 'Times Roman',
        'courier': 'Courier',
        'espaciado': 'Espaciado',
        'compacto': 'Compacto',
        'normal': 'Normal',
        'espacioso': 'Espacioso',
        'tipo_de_grafico': 'Tipo de gráfico',
        'barras': 'Barras',
        'pastel_pie': 'Pastel (Pie)',
        'orientacion_horizontal_landscape': 'Orientación horizontal (Landscape)',
        'descargar': 'Descargar',
        'atras': 'Atrás',
        'expira_en': 'Expira en ',
        'tus_presets_guardados': 'Tus presets guardados',
        'selecciona_un_preset_para_sobrescribir_los_colores': 'Selecciona un preset para sobrescribir los colores.',
        'guardar_como_preset': 'Guardar como preset',
        'guardar_preset_personalizado': 'Guardar preset personalizado',
        'nombre_del_preset': 'Nombre del preset',
        'mi_preset': 'Mi preset',
        'icono': 'Icono',
        'aplicar_preset': '¿Aplicar preset?',
        'se_sobrescribiran_los_colores_actuales_con_los_del_preset_guardado': 'Se sobrescribirán los colores actuales con los del preset guardado.',
        'se_eliminara_permanentemente': 'Este preset guardado se eliminará permanentemente.',
        'haz_clic_para_seleccionar_podras_recortar_la_imagen_antes_de_guardar': 'Haz clic para seleccionar. Podrás recortar la imagen antes de guardar.',
        'aplicar_recorte': 'Aplicar recorte',
        'cambiar_contrasena': 'Cambiar Contraseña',
        'registro_de_actividad': 'Registro de Actividad',
        'registro_de_actividad_del_sistema': 'Registro de Actividad del Sistema',
        'seleccionar_todos': 'Seleccionar todos',
        'eliminar_seleccionados': 'Eliminar seleccionados',
        'accion': 'Acción',
        'modelo': 'Modelo',
        'objeto': 'Objeto',
        'ip': 'IP',
        'no_hay_registros_de_actividad': 'No hay registros de actividad.',
        'nuevo_cliente': '+ Nuevo Cliente',
        'buscar_por_nombre_telefono_o_mac': 'Buscar por nombre, teléfono o MAC...',
        'buscar_por_nombre_telefono': 'Buscar por nombre o teléfono...',
        'datos_adicionales': 'Datos adicionales',
        'dispositivo': 'Dispositivo',
        'acciones': 'Acciones',
        'ver': 'Ver',
        'editar': 'Editar',
        'no_hay_clientes_registrados': 'No hay clientes registrados',
        'anterior': 'Anterior',
        'siguiente': 'Siguiente',
        'datos': 'Datos',
        'activo': 'Activo',
        'si': 'Sí',
        'no': 'No',
        'nueva': '+ Nueva',
        'plan': 'Plan',
        'inicio': 'Inicio',
        'vencimiento': 'Vencimiento',
        'estado': 'Estado',
        'recordatorio': 'Recordatorio',
        'sin_suscripciones': 'Sin suscripciones',
        'anotaciones': 'Anotaciones',
        'nueva_anotacion': 'Nueva anotación...',
        'agregar': 'Agregar',
        'sin_anotaciones': 'Sin anotaciones',
        'historial': 'Historial',
        'agregar_nota_al_historial': 'Agregar nota al historial...',
        'sin_historial': 'Sin historial',
        'desactivar_cliente': 'Desactivar Cliente',
        'desactivar': 'Desactivar',
        'si_desactivar': 'Sí, desactivar',
        'todos_los_estados': 'Todos los estados',
        'cancelado': 'Cancelado',
        'renovar': 'Renovar',
        'no_hay_suscripciones': 'No hay suscripciones',
        'nueva_suscripcion': '+ Nueva Suscripción',
        'nuevo_movimiento': '+ Nuevo Movimiento',
        'movimientos_financieros': 'Movimientos Financieros',
        'todos': 'Todos',
        'ingresos': 'Ingresos',
        'egresos': 'Egresos',
        'sin_movimientos_financieros': 'Sin movimientos',
        'registrar_movimiento': 'Registrar Movimiento',
        'log_de_notificaciones': 'Log de Notificaciones',
        'canal': 'Canal',
        'destinatario': 'Destinatario',
        'enviado': '✓ Enviado',
        'fallo': '✗ Falló',
        'sin_notificaciones': 'Sin notificaciones',
        'bloqueado': 'Bloqueado',
        'cuenta_bloqueada': 'Cuenta Bloqueada',
        'demasiados_intentos_fallidos_intenta_de_nuevo_mas_tarde': 'Demostrados intentos fallidos. Intenta de nuevo más tarde.',
        'volver_al_login': 'Volver al login',
        'sistema_de_gestion_de_servicios_iptv': 'Sistema de Gestión de Servicios IPTV',
        'iptv_manager_es_un_sistema_integral': 'IPTV Manager es un sistema integral para la administración de pequeñas y medianas empresas proveedoras de servicios IPTV.',
        'clientes_activos_estadistica': 'Clientes activos',
        'suscripciones_activas_estadistica': 'Suscripciones activas',
        'planes_disponibles': 'Planes disponibles',
        'acerca_de': 'Acerca de',
        'gestiona_clientes_asigna_suscripciones_controla_finanzas_y_automatiza_recordatorios': 'Gestiona clientes, asigna suscripciones, controla finanzas y automatiza recordatorios — todo desde un solo lugar.',
        'fondo_pixel_art': 'Fondo pixel art',
        'ninguno': 'Ninguno',
        'estrellas': 'Estrellas',
        'cuadricula': 'Cuadrícula',
        'ajedrez': 'Ajedrez',
        'circuitos': 'Circuitos',
        'diamantes': 'Diamantes',
        'lluvia': 'Lluvia',
        'montanas': 'Montañas',
        'nebulosa': 'Nebulosa',
        'matrix': 'Matrix',
        'total_cliente': 'Total clientes:',
        'subs_act': 'Subs Act.',
        'total_gastado': 'Total Gastado',
        'tareas': 'Tareas',
        'usuarios': 'Usuarios',
        'personalizar_pagina_500': 'Personalizar página 500',
        'personalizar_paginas_error': 'Páginas de error',
        'paginas_error': 'Páginas de error',
        'config_500_desc': 'Configura cómo se ve la página cuando ocurre un error interno del servidor.',
        'color_fondo': 'Color de fondo',
        'color_texto': 'Color de texto',
        'mostrar_arte_pixelado_500': 'Mostrar arte pixelado (volcán y lava)',
        'text_border_color': 'Color del borde de texto',
        'text_border_width': 'Grosor del borde de texto',
        'galeria_fotos': 'Galería de Fotos',
        'sin_imagenes': 'No hay imágenes disponibles',
        'whatsapp_config': 'WhatsApp',
        'whatsapp_status': 'Estado de WhatsApp',
        'whatsapp_connected': 'WhatsApp está conectado y listo para enviar mensajes',
        'conectado': 'Conectado',
        'conectando': 'Conectando',
        'desconectado': 'Desconectado',
        'desconectar': 'Desconectar',
        'esperando_qr': 'Esperando código QR...',
        'instructions': 'Instrucciones:',
        'whatsapp_instruction_1': 'Abre WhatsApp en tu celular.',
        'whatsapp_instruction_2': 'Ve a Menú > WhatsApp Web > Escanear código.',
        'whatsapp_instruction_3': 'Escanea el código QR que aparece arriba.',
        'confirm_desconectar': '¿Estás seguro de desconectar WhatsApp?',
        'refresh': 'Actualizar',
        'reminder_templates': 'Plantillas de recordatorio',
        'reminder_templates_desc': 'Personaliza el mensaje que se enviará como recordatorio a los clientes.',
        'new_template': 'Nueva plantilla',
        'no_templates': 'No hay plantillas de recordatorio',
        'template': 'plantilla',
        'available_placeholders': 'Placeholders disponibles',
        'placeholder_cliente': 'Nombre del cliente',
        'placeholder_plan': 'Nombre del plan',
        'placeholder_vencimiento': 'Fecha de vencimiento',
        'placeholder_precio': 'Precio de la suscripción',
        'template_active_help': 'Solo una plantilla activa será usada para enviar recordatorios.',
        'create_first_template': 'Crear primera plantilla',
        'delete_template_confirm': '¿Estás seguro de eliminar la plantilla?',
        'inactivo': 'Inactivo',
        'created_by': 'Creado por',
        'template_active_info': 'Esta plantilla está activa y se usará para los recordatorios automáticos.',
        'enviar_recordatorio': 'Enviar mensaje',
        'seleccionar_cliente': 'Seleccionar cliente',
        'seleccionar_plantillas': 'Seleccionar plantilla(s)',
        'seleccionar': 'Seleccionar',
        'enviar_por_whatsapp': 'Enviar por WhatsApp',
        'enviar_por_whatsapp_help': 'Si desmarcas, solo se mostrará la vista previa sin enviar.',
        'enviar': 'Enviar',
        'selecciona_cliente_plantilla': 'Selecciona un cliente y al menos una plantilla para ver la vista previa.',
        'no_active_templates': 'No hay plantillas activas',
        'categoria': 'Categoría',
        'vencimiento': 'Vencimiento',
        'bienvenida': 'Bienvenida',
        'oferta': 'Oferta',
        'personalizado': 'Personalizado',
        'recordatorio_de_vencimiento': 'Recordatorio de vencimiento',
        'bienvenida_asignacion': 'Bienvenida / Asignación',
        'oferta_promocion': 'Oferta / Promoción',
        'mensajes_mes': 'Mensajes mes',
        'enviados_ok': 'Enviados OK',
        'fallidos': 'Fallidos',
        'por_ciento_exito': '% Éxito',
        'email_whatsapp': 'Email / WhatsApp',
        'mensajes_ultimos_30_dias': 'Mensajes últimos 30 días',
        'exito_fracaso': 'Éxito / Fracaso',
        'neto_mensual_chart': 'Neto mensual',
        'suscripciones_chart': 'Suscripciones',
        'prediccion_neto_chart': 'Predicción neto ($)',
        'mensajes_chart': 'Mensajes',
        'exitosos': 'Exitosos',
        'cancelar_suscripcion': '¿Cancelar esta suscripción?',
        'cancelar_btn': 'Cancelar',
        'desactivar_esta_cuenta': '¿Desactivar este cliente?',
        'desactivar_confirm_msg': 'Este cliente tiene <strong>%s suscripción(es) activa(s)</strong> que serán canceladas automáticamente. ¿Desactivar de todas formas?',
        'desactivar_cliente_modal': 'Desactivar cliente',
        'cancelar_suscripcion_modal': '¿Cancelar?',
        'renovar_suscripcion_modal': '¿Renovar?',
        'eliminar_tarea_modal': '¿Eliminar tarea?',
        'precio_del_plan': 'Precio del plan:',
        'precio_final': 'Precio final:',
        'actualizar': 'Actualizar',
        'descuento_no_negativo': 'El descuento no puede ser negativo.',
        'descuento_porcentual_no_supera_100': 'El descuento porcentual no puede superar el 100%.',
        'descuento_fijo_no_supera_precio': 'El descuento fijo no puede superar el precio del plan ($%s).',
        'usuarios_del_sistema': 'Usuarios del Sistema',
        'sin_grupo': 'Sin grupo',
        'nunca': 'Nunca',
        'no_hay_usuarios': 'No hay usuarios registrados',
        'lista_de_tareas': 'Lista de Tareas',
        'nueva_tarea': 'Nueva tarea',
        'crear_tarea': 'Crear tarea',
        'filtros': 'Filtros',
        'todas': 'Todas',
        'pendientes': 'Pendientes',
        'completadas': 'Completadas',
        'no_hay_tareas': 'No hay tareas',
        'registros': 'registros',
        'usuario_tabla': 'Usuario',
        'reportar_error': 'Reportar error',
        'que_estabas_haciendo': '¿Qué estabas haciendo cuando ocurrió el error?',
        'enviar_reporte': 'Enviar reporte',
        'gestiona_clientes_asigna_suscripciones_controla_finanzas_y_automatiza_recordatorios_todo_desde_un_solo_lugar': 'Gestiona clientes, asigna suscripciones, controla finanzas y automatiza recordatorios — todo desde un solo lugar.',
        'iniciar_sesion_btn': 'Iniciar Sesión',
        'acerca_de_btn': 'Acerca de',
        'documentacion_btn': 'Documentación',
        'url_de_imagen_opcional': 'URL de imagen (opcional)',
        'url_ejemplo_placeholder': 'https://ejemplo.com/imagen.jpg',
        'url_imagen_help': 'Si agregas una URL, se enviará como imagen adjunta con el texto de la plantilla. Los emojis se pueden escribir directamente en el mensaje.',
        'personalizar_pagina_error_500': 'Personalizar página 500',
        'color_ingresos': 'Color de ingresos (gráfico)',
        'color_egresos': 'Color de egresos (gráfico)',
        'vista_previa_btn': 'Vista Previa',
        'vista_previa_reporte': 'Vista Previa Reporte',
        'elige_preset_o_personaliza': 'Elige uno de los 5 presets predefinidos, aplica un preset guardado, o personaliza los colores manualmente.',
        'negrilla': 'Negrilla',
        'italica': 'Itálica',
        'subrayado': 'Subrayado',
        'tachado': 'Tachado',
        'guardar_tema': 'Guardar tema',
        'negrita': 'Negrita',
        'cursiva': 'Cursiva',
        'email': 'Email:',
        'dispositivo_label': 'Dispositivo:',
        'documento_label': 'Documento:',
        'registro_label': 'Registro:',
        'activo_label': 'Activo:',
        'no_hay_planes': 'No hay planes disponibles',
        'lista_de_planes': 'Lista de Planes',
        'nuevo_plan': '+ Nuevo Plan',
        'duracion_dias': 'Duración (días)',
        'precio': 'Precio',
        'planes': 'Planes',
        'guardar_plan': 'Guardar Plan',
        'editar_plan': 'Editar Plan',
        'eliminar_plan': '¿Eliminar este plan?',
        'nombre_del_cliente': 'Nombre del cliente',
        'foto_del_cliente': 'Foto del cliente',
        'foto_opcional': 'Foto (opcional)',
        'seleccionar_archivo': 'Seleccionar archivo',
        'ningun_archivo_seleccionado': 'Ningún archivo seleccionado',
        'nueva_nota_historial': 'Agregar nota al historial...',
        'nota_placeholder': 'Escribe una nota...',
        'si_cancelar': 'Sí, cancelar',
        'si_renovar': 'Sí, renovar',
        'plan_label': 'Plan:',
        'metodo_pago_label': 'Método de pago:',
        'fecha_inicio': 'Fecha de inicio',
        'fecha_vencimiento': 'Fecha de vencimiento',
        'descuento_porcentaje': 'Descuento (%)',
        'descuento_fijo': 'Descuento fijo ($)',
        'precio_final_label': 'Precio final:',
        'actualizar_suscripcion': 'Actualizar Suscripción',
        'crear_suscripcion': 'Crear Suscripción',
        'tipo_transaccion': 'Tipo',
        'monto_label': 'Monto',
        'descripcion_label': 'Descripción',
        'fecha_label': 'Fecha',
        'crear_movimiento': 'Crear Movimiento',
        'clientes_heading': 'Clientes',
        'clientes_title': 'Clientes',
        'planes_title': 'Planes',
        'suscripciones_title': 'Suscripciones',
        'usuarios_title': 'Usuarios',
        'tareas_title': 'Tareas',
        'actividad_title': 'Actividad',
        'finanzas_title': 'Finanzas',
        'reportes_title': 'Reportes',
        'galeria_title': 'Galería',
        'whatsapp_title': 'WhatsApp',
        'tema_title': 'Personalizar Tema',
        'sesion_title': 'Tiempo de sesión',
        'actualizar_sistema': 'Actualizar sistema',
        'agregar_una_funcionalidad_nueva': 'Agregar una funcionalidad nueva',
        'ajax_dinamico_sin_recargas': 'AJAX dinámico sin recargas.',
        'ajax_sin_javascript': 'AJAX sin JavaScript.',
        'api_de_mensajeria_whatsapp': 'API de mensajería WhatsApp.',
        'arquitectura': 'Arquitectura',
        'arquitectura_del_sistema': 'Arquitectura del Sistema',
        'arrancar_en_desarrollo': 'Arrancar en desarrollo',
        'backend': 'Backend',
        'base_de_datos_relacional': 'Base de datos relacional.',
        'bd_ligera_desarrollo_local': 'BD ligera desarrollo local.',
        'bd_relacional_produccion': 'BD relacional producción.',
        'cada_medida_de_seguridad_implementada_incluye_una_explicacion_de_que_protege_y_como_funciona_haz_clic_en_cada_una_para_expandir': 'Cada medida de seguridad implementada incluye una explicación de qué protege y cómo funciona. Haz clic en cada una para expandir.',
        'clickjacking_frame_options': 'Clickjacking (Frame Options)',
        'cliente_http': 'Cliente HTTP.',
        'comandos_diarios': 'Comandos diarios',
        'componentes_del_sistema': 'Componentes del sistema',
        'contenedores_multiservicio': 'Contenedores multi-servicio.',
        'content_sniffing_mime_sniffing': 'Content Sniffing (MIME sniffing)',
        'cookies_seguras_secure_httponly': 'Cookies Seguras (Secure + HttpOnly)',
        'csrf_crosssite_request_forgery': 'CSRF (Cross-Site Request Forgery)',
        'dashboard_y_analitica': 'Dashboard y Analítica',
        'debug_mode': 'DEBUG mode',
        'diagrama_entidadrelacion_del_sistema_las_flechas_indican_relaciones_foreignkey': 'Diagrama entidad-relación del sistema. Las flechas indican relaciones ForeignKey.',
        'driver_postgresql': 'Driver PostgreSQL.',
        'en_todos_los_formularios': ' en todos los formularios',
        'estructura_de_archivos': 'Estructura de Archivos',
        'flujo_de_una_peticion': 'Flujo de una petición',
        'framework_css_utilityfirst': 'Framework CSS utility-first.',
        'framework_web_mtv_con_orm': 'Framework web MTV con ORM.',
        'frontend': 'Frontend',
        'fuerza_bruta_djangoaxes': 'Fuerza Bruta (django-axes)',
        'graficos_interactivos': 'Gráficos interactivos.',
        'guia_dev': 'Guía Dev',
        'guia_para_desarrolladores': 'Guía para Desarrolladores',
        'hsts_http_strict_transport_security': 'HSTS (HTTP Strict Transport Security)',
        'iconos_vectoriales': 'Iconos vectoriales.',
        'implementacion_100_orm_autoescape_templates_sin_mark_safe': 'Implementación: 100% ORM + auto-escape templates, sin mark_safe',
        'implementacion_5_intentos_1h_cooloff_bloqueo_ipusuario': 'Implementación: 5 intentos, 1h cooloff, bloqueo IP+usuario',
        'implementacion_31536000s_1_ano_includesubdomains_preload': 'Implementación: 31536000s (1 año), includeSubDomains, preload',
        'implementacion_csrfviewmiddleware': 'Implementación: CsrfViewMiddleware + ',
        'implementacion_false_por_defecto_via_env_var': 'Implementación: False por defecto vía env var',
        'implementacion_login_required_permissionrequiredmixin_en_todas_las_vistas': 'Implementación: @login_required + PermissionRequiredMixin en TODAS las vistas',
        'implementacion_pythondecouple_sin_default_en_codigo': 'Implementación: python-decouple, sin default en código',
        'implementacion_regexvalidator_para_e164_y_xxxxxxxxxxxx': 'Implementación: RegexValidator para E.164 y XX:XX:XX:XX:XX:XX',
        'implementacion_secure_browser_xss_filter_true': 'Implementación: SECURE_BROWSER_XSS_FILTER = True',
        'implementacion_secure_content_type_nosniff_true': 'Implementación: SECURE_CONTENT_TYPE_NOSNIFF = True',
        'implementacion_session_cookie_secure_csrf_cookie_secure_condicional_a_https': 'Implementación: SESSION_COOKIE_SECURE + CSRF_COOKIE_SECURE condicional a HTTPS',
        'implementacion_x_frame_options_deny': 'Implementación: X_FRAME_OPTIONS = \'DENY\'',
        'infraestructura': 'Infraestructura',
        'lenguaje_principal_del_backend': 'Lenguaje principal del backend.',
        'mantenimiento': 'Mantenimiento',
        'modelos': 'Modelos',
        'modelos_y_relaciones': 'Modelos y Relaciones',
        'monitoreo_de_seguridad': 'Monitoreo de seguridad',
        'procesamiento_imagenes': 'Procesamiento imágenes.',
        'proteccion_fuerza_bruta': 'Protección fuerza bruta.',
        'proteccion_sqli_xss_en_bd': 'Protección SQLi / XSS en BD',
        'rbac_control_de_acceso_por_roles': 'RBAC (Control de Acceso por Roles)',
        'respaldar_restaurar': 'Respaldar / Restaurar',
        'reverse_proxy_ssl_estaticos': 'Reverse proxy, SSL, estáticos.',
        'secret_key': 'Secret Key',
        'seguridad': 'Seguridad',
        'sirve_archivos_estaticos': 'Sirve archivos estáticos.',
        'sistema_de_plantillas_nativo': 'Sistema de plantillas nativo.',
        'stack_tecnologico': 'Stack Tecnológico',
        'tecnologias': 'Tecnologías',
        'tecnologias_arquitectura_y_guia_para_desarrolladores': 'Tecnologías, arquitectura y guía para desarrolladores.',
        'tests': 'Tests',
        'validacion_de_input_telefono_mac': 'Validación de Input (teléfono, MAC)',
        'variables_de_entorno_env': 'Variables de entorno (.env)',
        'wsgi_server_para_produccion': 'WSGI server para producción.',
        'xss_crosssite_scripting': 'XSS (Cross-Site Scripting)',
        'resetear_tiempo_sesion': 'Reiniciar tiempo de sesión',
        'tiempo_reiniciado': '¡Tiempo de sesión reiniciado!',
    },
    'en': {
        'dashboard': 'Dashboard',
        'clientes': 'Clients',
        'suscripciones': 'Subscriptions',
        'finanzas': 'Finance',
        'notificaciones': 'Notifications',
        'actividad': 'Activity',
        'admin_django': 'Django Admin',
        'mi_perfil': 'My Profile',
        'reportes': 'Reports',
        'personalizar_tema': 'Customize Theme',
        'personalizar_404': 'Customize 404',
        'tiempo_de_sesion': 'Session Time',
        'documentacion': 'Documentation',
        'acerca_de_uso': 'About / Usage',
        'modo_oscuro': 'Dark mode',
        'cerrar_sesion': 'Sign out',
        'tu_sesion_esta_por_expirar': 'Your session is about to expire',
        'extender_sesion': 'Extend session',
        'estas_seguro': 'Are you sure?',
        'esta_accion_no_se_puede_deshacer': 'This action cannot be undone.',
        'cancelar': 'Cancel',
        'eliminar': 'Delete',
        'bienvenido': 'Welcome, %s!',
        'sin_grupo_asignado': 'No group assigned',
        'admin_maestro': 'Master Admin',
        'miembro_desde': 'Member since:',
        'ultimo_acceso': 'Last login:',
        'primera_vez': 'First time',
        'sin_email': 'No email',
        'editar_perfil': 'Edit profile',
        'clientes_activos': 'Active Clients',
        'suscripciones_activas': 'Active Subscriptions',
        'por_vencer': 'Expiring Soon (3 days)',
        'vencidas': 'Expired',
        'saldo_del_mes': 'Month Balance',
        'ingresos_vs_egresos': 'Income vs Expenses (6 months)',
        'distribucion_por_plan': 'Distribution by Plan',
        'suscripciones_temporales': 'Temporal Subscriptions',
        'ingresos_este_mes': 'Income this month:',
        'egresos_este_mes': 'Expenses this month:',
        'suscripciones_activas_label': 'Active subscriptions:',
        'por_vencer_proximamente': 'Expiring soon:',
        'vencidas_label': 'Expired:',
        'ultimos_movimientos': 'Latest Transactions',
        'ultimos_clientes': 'Latest Clients',
        'ir_al_inicio': 'Go to home',
        'iniciar_sesion': 'Sign in',
        'ayuda': 'Help',
        'personalizar_pagina_404': 'Customize 404 page',
        'config_404_desc': 'Configure how the page looks when someone visits a URL that doesn\'t exist.',
        'titulo': 'Title',
        'mensaje': 'Message',
        'mostrar_arte_pixelado': 'Show pixel art (castle and stars)',
        'guardar': 'Save',
        'volver': 'Go back',
        'vista_previa': 'Preview',
        'configuracion_de_sesion': 'Session Configuration',
        'config_sesion_desc': 'Set how often the session automatically expires due to inactivity.',
        'guardar_cambios': 'Save changes',
        'cambiar_contraseña': 'Change password',
        'recortar_foto': 'Crop photo',
        'iniciar_sesion_title': 'Sign In',
        'usuario': 'Username',
        'contraseña': 'Password',
        'credenciales_incorrectas': 'Invalid username or password.',
        'entrar': 'Sign in',
        'neto_mensual': 'Monthly Net',
        'prediccion_de_gananciasperdidas': 'Profit/Loss Prediction',
        'basado_en_regresion_lineal_simple_sobre_los_ultimos_6_meses': 'Based on simple linear regression over the last 6 months',
        'resumen_ejecutivo': 'Executive Summary',
        'neto_del_mes': 'Month net:',
        'clientes_activos_label': 'Active clients:',
        'tipo': 'Type',
        'monto': 'Amount',
        'fecha': 'Date',
        'descripcion': 'Description',
        'sin_movimientos': 'No transactions',
        'nombre': 'Name',
        'telefono': 'Phone',
        'registro': 'Registered',
        'sin_clientes': 'No clients',
        'documento_identidad': 'ID Document',
        'metodo_pago': 'Payment Method',
        'efectivo': 'Cash',
        'cheque': 'Check',
        'tarjeta_debito': 'Debit Card',
        'cortesia': 'Courtesy',
        'como_usar_el_sistema': 'How to use the system',
        'como_usar_iptv_manager': 'How to use IPTV Manager',
        'guia_paso_a_paso_para_operar_el_sistema': 'Step-by-step guide to operate the system.',
        'primeros_pasos': 'First steps',
        'gestion_de_clientes': 'Client Management',
        'suscripciones_y_planes': 'Subscriptions & Plans',
        'personalizacion': 'Customization',
        'roles_y_permisos': 'Roles & Permissions',
        'solucion_de_problemas': 'Troubleshooting',
        'generar_reporte': 'Generate Report',
        'selecciona_las_secciones_el_formato_y_el_diseno_para_tu_reporte': 'Select sections, format and design for your report.',
        'secciones': 'Sections',
        'periodo_opcional': 'Period (optional)',
        'desde': 'From',
        'hasta': 'To',
        'formato_y_diseno': 'Format & Design',
        'formato_de_salida': 'Output format',
        'plantilla_pdf': 'PDF Template',
        'pdf': 'PDF',
        'excel': 'Excel',
        'jpg_vista_previa': 'JPG (Preview)',
        'ajustes_pdf': 'PDF Settings',
        'margenes': 'Margins',
        'pequenos_15_cm': 'Small (1.5 cm)',
        'normales_254_cm': 'Normal (2.54 cm)',
        'grandes_30_cm': 'Large (3.0 cm)',
        'tipografia': 'Font',
        'helvetica_arial': 'Helvetica (Arial)',
        'times_roman': 'Times Roman',
        'courier': 'Courier',
        'espaciado': 'Spacing',
        'compacto': 'Compact',
        'normal': 'Normal',
        'espacioso': 'Spacious',
        'tipo_de_grafico': 'Chart type',
        'barras': 'Bar',
        'pastel_pie': 'Pie',
        'orientacion_horizontal_landscape': 'Landscape orientation',
        'descargar': 'Download',
        'atras': 'Back',
        'expira_en': 'Expires in ',
        'tus_presets_guardados': 'Your saved presets',
        'selecciona_un_preset_para_sobrescribir_los_colores': 'Select a preset to overwrite colors.',
        'guardar_como_preset': 'Save as preset',
        'guardar_preset_personalizado': 'Save custom preset',
        'nombre_del_preset': 'Preset name',
        'mi_preset': 'My preset',
        'icono': 'Icon',
        'aplicar_preset': 'Apply preset?',
        'se_sobrescribiran_los_colores_actuales_con_los_del_preset_guardado': 'Current colors will be overwritten with the saved preset.',
        'se_eliminara_permanentemente': 'This saved preset will be permanently deleted.',
        'haz_clic_para_seleccionar_podras_recortar_la_imagen_antes_de_guardar': 'Click to select. You can crop the image before saving.',
        'aplicar_recorte': 'Apply crop',
        'cambiar_contrasena': 'Change Password',
        'registro_de_actividad': 'Activity Log',
        'registro_de_actividad_del_sistema': 'System Activity Log',
        'seleccionar_todos': 'Select all',
        'eliminar_seleccionados': 'Delete selected',
        'accion': 'Action',
        'modelo': 'Model',
        'objeto': 'Object',
        'ip': 'IP',
        'no_hay_registros_de_actividad': 'No activity records.',
        'nuevo_cliente': '+ New Client',
        'buscar_por_nombre_telefono_o_mac': 'Search by name, phone or MAC...',
        'buscar_por_nombre_telefono': 'Search by name or phone...',
        'datos_adicionales': 'Additional Data',
        'dispositivo': 'Device',
        'acciones': 'Actions',
        'ver': 'View',
        'editar': 'Edit',
        'no_hay_clientes_registrados': 'No registered clients',
        'anterior': 'Previous',
        'siguiente': 'Next',
        'datos': 'Data',
        'activo': 'Active',
        'si': 'Yes',
        'no': 'No',
        'nueva': '+ New',
        'plan': 'Plan',
        'inicio': 'Start',
        'vencimiento': 'Expiry',
        'estado': 'Status',
        'recordatorio': 'Reminder',
        'sin_suscripciones': 'No subscriptions',
        'anotaciones': 'Notes',
        'nueva_anotacion': 'New note...',
        'agregar': 'Add',
        'sin_anotaciones': 'No notes',
        'historial': 'History',
        'agregar_nota_al_historial': 'Add note to history...',
        'sin_historial': 'No history',
        'desactivar_cliente': 'Deactivate Client',
        'desactivar': 'Deactivate',
        'si_desactivar': 'Yes, deactivate',
        'todos_los_estados': 'All statuses',
        'cancelado': 'Canceled',
        'renovar': 'Renew',
        'no_hay_suscripciones': 'No subscriptions',
        'nueva_suscripcion': '+ New Subscription',
        'nuevo_movimiento': '+ New Transaction',
        'movimientos_financieros': 'Financial Transactions',
        'todos': 'All',
        'ingresos': 'Income',
        'egresos': 'Expenses',
        'sin_movimientos_financieros': 'No transactions',
        'registrar_movimiento': 'Register Transaction',
        'log_de_notificaciones': 'Notification Log',
        'canal': 'Channel',
        'destinatario': 'Recipient',
        'enviado': '✓ Sent',
        'fallo': '✗ Failed',
        'sin_notificaciones': 'No notifications',
        'bloqueado': 'Locked',
        'cuenta_bloqueada': 'Account Locked',
        'demasiados_intentos_fallidos_intenta_de_nuevo_mas_tarde': 'Too many failed attempts. Try again later.',
        'volver_al_login': 'Back to login',
        'sistema_de_gestion_de_servicios_iptv': 'IPTV Service Management System',
        'iptv_manager_es_un_sistema_integral': 'IPTV Manager is a comprehensive system for managing small and medium IPTV service providers.',
        'clientes_activos_estadistica': 'Active Clients',
        'suscripciones_activas_estadistica': 'Active Subscriptions',
        'planes_disponibles': 'Available Plans',
        'acerca_de': 'About',
        'gestiona_clientes_asigna_suscripciones_controla_finanzas_y_automatiza_recordatorios': 'Manage clients, assign subscriptions, control finances and automate reminders — all from one place.',
        'fondo_pixel_art': 'Pixel art background',
        'ninguno': 'None',
        'estrellas': 'Stars',
        'cuadricula': 'Grid',
        'ajedrez': 'Checkerboard',
        'circuitos': 'Circuits',
        'diamantes': 'Diamonds',
        'lluvia': 'Rain',
        'montanas': 'Mountains',
        'nebulosa': 'Nebula',
        'matrix': 'Matrix',
        'total_cliente': 'Total clients:',
        'subs_act': 'Active Subs',
        'total_gastado': 'Total Spent',
        'tareas': 'Tasks',
        'usuarios': 'Users',
        'personalizar_pagina_500': 'Customize 500 page',
        'personalizar_paginas_error': 'Error pages',
        'paginas_error': 'Error pages',
        'config_500_desc': 'Configure how the page looks when an internal server error occurs.',
        'color_fondo': 'Background color',
        'color_texto': 'Text color',
        'mostrar_arte_pixelado_500': 'Show pixel art (volcano and lava)',
        'text_border_color': 'Text border color',
        'text_border_width': 'Text border width',
        'galeria_fotos': 'Photo Gallery',
        'sin_imagenes': 'No images available',
        'whatsapp_config': 'WhatsApp',
        'whatsapp_status': 'WhatsApp Status',
        'whatsapp_connected': 'WhatsApp is connected and ready to send messages',
        'conectado': 'Connected',
        'conectando': 'Connecting',
        'desconectado': 'Disconnected',
        'desconectar': 'Disconnect',
        'esperando_qr': 'Waiting for QR code...',
        'instructions': 'Instructions:',
        'whatsapp_instruction_1': 'Open WhatsApp on your phone.',
        'whatsapp_instruction_2': 'Go to Menu > WhatsApp Web > Scan code.',
        'whatsapp_instruction_3': 'Scan the QR code shown above.',
        'confirm_desconectar': 'Are you sure you want to disconnect WhatsApp?',
        'refresh': 'Refresh',
        'reminder_templates': 'Reminder Templates',
        'reminder_templates_desc': 'Customize the message sent as a reminder to clients.',
        'new_template': 'New template',
        'no_templates': 'No reminder templates',
        'template': 'template',
        'available_placeholders': 'Available placeholders',
        'placeholder_cliente': 'Client name',
        'placeholder_plan': 'Plan name',
        'placeholder_vencimiento': 'Expiration date',
        'placeholder_precio': 'Subscription price',
        'template_active_help': 'Only one active template will be used for sending reminders.',
        'create_first_template': 'Create first template',
        'delete_template_confirm': 'Are you sure you want to delete the template?',
        'inactivo': 'Inactive',
        'created_by': 'Created by',
        'template_active_info': 'This template is active and will be used for automatic reminders.',
        'enviar_recordatorio': 'Send message',
        'seleccionar_cliente': 'Select client',
        'seleccionar_plantillas': 'Select template(s)',
        'seleccionar': 'Select',
        'enviar_por_whatsapp': 'Send via WhatsApp',
        'enviar_por_whatsapp_help': 'If unchecked, only the preview will be shown without sending.',
        'enviar': 'Send',
        'selecciona_cliente_plantilla': 'Select a client and at least one template to see the preview.',
        'no_active_templates': 'No active templates',
        'categoria': 'Category',
        'vencimiento': 'Expiration',
        'bienvenida': 'Welcome',
        'oferta': 'Offer',
        'personalizado': 'Custom',
        'recordatorio_de_vencimiento': 'Expiration reminder',
        'bienvenida_asignacion': 'Welcome / Assignment',
        'oferta_promocion': 'Offer / Promotion',
        'mensajes_mes': 'Messages this month',
        'enviados_ok': 'Sent OK',
        'fallidos': 'Failed',
        'por_ciento_exito': '% Success',
        'email_whatsapp': 'Email / WhatsApp',
        'mensajes_ultimos_30_dias': 'Last 30 days messages',
        'exito_fracaso': 'Success / Failure',
        'neto_mensual_chart': 'Monthly Net',
        'suscripciones_chart': 'Subscriptions',
        'prediccion_neto_chart': 'Net Prediction ($)',
        'mensajes_chart': 'Messages',
        'exitosos': 'Successful',
        'cancelar_suscripcion': 'Cancel this subscription?',
        'cancelar_btn': 'Cancel',
        'desactivar_esta_cuenta': 'Deactivate this client?',
        'desactivar_confirm_msg': 'This client has <strong>%s active subscription(s)</strong> that will be canceled automatically. Deactivate anyway?',
        'desactivar_cliente_modal': 'Deactivate client',
        'cancelar_suscripcion_modal': 'Cancel?',
        'renovar_suscripcion_modal': 'Renew?',
        'eliminar_tarea_modal': 'Delete task?',
        'precio_del_plan': 'Plan price:',
        'precio_final': 'Final price:',
        'actualizar': 'Update',
        'descuento_no_negativo': 'Discount cannot be negative.',
        'descuento_porcentual_no_supera_100': 'Percentage discount cannot exceed 100%.',
        'descuento_fijo_no_supera_precio': 'Fixed discount cannot exceed the plan price ($%s).',
        'usuarios_del_sistema': 'System Users',
        'sin_grupo': 'No group',
        'nunca': 'Never',
        'no_hay_usuarios': 'No registered users',
        'lista_de_tareas': 'Task List',
        'nueva_tarea': 'New task',
        'crear_tarea': 'Create task',
        'filtros': 'Filters',
        'todas': 'All',
        'pendientes': 'Pending',
        'completadas': 'Completed',
        'no_hay_tareas': 'No tasks',
        'registros': 'records',
        'usuario_tabla': 'User',
        'reportar_error': 'Report error',
        'que_estabas_haciendo': 'What were you doing when the error occurred?',
        'enviar_reporte': 'Send report',
        'gestiona_clientes_asigna_suscripciones_controla_finanzas_y_automatiza_recordatorios_todo_desde_un_solo_lugar': 'Manage clients, assign subscriptions, control finances and automate reminders — all from one place.',
        'iniciar_sesion_btn': 'Sign In',
        'acerca_de_btn': 'About',
        'documentacion_btn': 'Documentation',
        'url_de_imagen_opcional': 'Image URL (optional)',
        'url_ejemplo_placeholder': 'https://example.com/image.jpg',
        'url_imagen_help': 'If you add a URL, it will be sent as an attached image with the template text. Emojis can be typed directly in the message.',
        'personalizar_pagina_error_500': 'Customize 500 page',
        'color_ingresos': 'Income color (chart)',
        'color_egresos': 'Expense color (chart)',
        'vista_previa_btn': 'Preview',
        'vista_previa_reporte': 'Report Preview',
        'elige_preset_o_personaliza': 'Choose one of the 5 predefined presets, apply a saved preset, or customize colors manually.',
        'negrilla': 'Bold',
        'italica': 'Italic',
        'subrayado': 'Underline',
        'tachado': 'Strikethrough',
        'guardar_tema': 'Save theme',
        'negrita': 'Bold',
        'cursiva': 'Italic',
        'email': 'Email:',
        'dispositivo_label': 'Device:',
        'documento_label': 'Document:',
        'registro_label': 'Registered:',
        'activo_label': 'Active:',
        'no_hay_planes': 'No plans available',
        'lista_de_planes': 'Plans List',
        'nuevo_plan': '+ New Plan',
        'duracion_dias': 'Duration (days)',
        'precio': 'Price',
        'planes': 'Plans',
        'guardar_plan': 'Save Plan',
        'editar_plan': 'Edit Plan',
        'eliminar_plan': 'Delete this plan?',
        'nombre_del_cliente': 'Client name',
        'foto_del_cliente': 'Client photo',
        'foto_opcional': 'Photo (optional)',
        'seleccionar_archivo': 'Choose file',
        'ningun_archivo_seleccionado': 'No file selected',
        'nueva_nota_historial': 'Add note to history...',
        'nota_placeholder': 'Write a note...',
        'si_cancelar': 'Yes, cancel',
        'si_renovar': 'Yes, renew',
        'plan_label': 'Plan:',
        'metodo_pago_label': 'Payment method:',
        'fecha_inicio': 'Start date',
        'fecha_vencimiento': 'Expiration date',
        'descuento_porcentaje': 'Discount (%)',
        'descuento_fijo': 'Fixed discount ($)',
        'precio_final_label': 'Final price:',
        'actualizar_suscripcion': 'Update Subscription',
        'crear_suscripcion': 'Create Subscription',
        'tipo_transaccion': 'Type',
        'monto_label': 'Amount',
        'descripcion_label': 'Description',
        'fecha_label': 'Date',
        'crear_movimiento': 'Create Transaction',
        'clientes_heading': 'Clients',
        'clientes_title': 'Clients',
        'planes_title': 'Plans',
        'suscripciones_title': 'Subscriptions',
        'usuarios_title': 'Users',
        'tareas_title': 'Tasks',
        'actividad_title': 'Activity',
        'finanzas_title': 'Finance',
        'reportes_title': 'Reports',
        'galeria_title': 'Gallery',
        'whatsapp_title': 'WhatsApp',
        'tema_title': 'Customize Theme',
        'sesion_title': 'Session Time',
        'actualizar_sistema': 'Update System',
        'agregar_una_funcionalidad_nueva': 'Add a New Feature',
        'ajax_dinamico_sin_recargas': 'Dynamic AJAX without reloads.',
        'ajax_sin_javascript': 'AJAX without JavaScript.',
        'api_de_mensajeria_whatsapp': 'WhatsApp messaging API.',
        'arquitectura': 'Architecture',
        'arquitectura_del_sistema': 'System Architecture',
        'arrancar_en_desarrollo': 'Start in Development',
        'backend': 'Backend',
        'base_de_datos_relacional': 'Relational database.',
        'bd_ligera_desarrollo_local': 'Lightweight local development DB.',
        'bd_relacional_produccion': 'Production relational DB.',
        'cada_medida_de_seguridad_implementada_incluye_una_explicacion_de_que_protege_y_como_funciona_haz_clic_en_cada_una_para_expandir': 'Each implemented security measure includes an explanation of what it protects and how it works. Click on each one to expand.',
        'clickjacking_frame_options': 'Clickjacking (Frame Options)',
        'cliente_http': 'HTTP client.',
        'comandos_diarios': 'Daily Commands',
        'componentes_del_sistema': 'System Components',
        'contenedores_multiservicio': 'Multi-service containers.',
        'content_sniffing_mime_sniffing': 'Content Sniffing (MIME sniffing)',
        'cookies_seguras_secure_httponly': 'Secure Cookies (Secure + HttpOnly)',
        'csrf_crosssite_request_forgery': 'CSRF (Cross-Site Request Forgery)',
        'dashboard_y_analitica': 'Dashboard & Analytics',
        'debug_mode': 'DEBUG mode',
        'diagrama_entidadrelacion_del_sistema_las_flechas_indican_relaciones_foreignkey': 'Entity-relationship diagram of the system. Arrows indicate ForeignKey relationships.',
        'driver_postgresql': 'PostgreSQL driver.',
        'en_todos_los_formularios': ' in all forms',
        'estructura_de_archivos': 'File Structure',
        'flujo_de_una_peticion': 'Request Flow',
        'framework_css_utilityfirst': 'Utility-first CSS framework.',
        'framework_web_mtv_con_orm': 'MTV web framework with ORM.',
        'frontend': 'Frontend',
        'fuerza_bruta_djangoaxes': 'Brute Force (django-axes)',
        'graficos_interactivos': 'Interactive charts.',
        'guia_dev': 'Dev Guide',
        'guia_para_desarrolladores': 'Developer Guide',
        'hsts_http_strict_transport_security': 'HSTS (HTTP Strict Transport Security)',
        'iconos_vectoriales': 'Vector icons.',
        'implementacion_100_orm_autoescape_templates_sin_mark_safe': 'Implementation: 100% ORM + auto-escape templates, no mark_safe',
        'implementacion_5_intentos_1h_cooloff_bloqueo_ipusuario': 'Implementation: 5 attempts, 1h cooloff, IP+user lockout',
        'implementacion_31536000s_1_ano_includesubdomains_preload': 'Implementation: 31536000s (1 year), includeSubDomains, preload',
        'implementacion_csrfviewmiddleware': 'Implementation: CsrfViewMiddleware + ',
        'implementacion_false_por_defecto_via_env_var': 'Implementation: False by default via env var',
        'implementacion_login_required_permissionrequiredmixin_en_todas_las_vistas': 'Implementation: @login_required + PermissionRequiredMixin in ALL views',
        'implementacion_pythondecouple_sin_default_en_codigo': 'Implementation: python-decouple, no default in code',
        'implementacion_regexvalidator_para_e164_y_xxxxxxxxxxxx': 'Implementation: RegexValidator for E.164 and XX:XX:XX:XX:XX:XX',
        'implementacion_secure_browser_xss_filter_true': 'Implementation: SECURE_BROWSER_XSS_FILTER = True',
        'implementacion_secure_content_type_nosniff_true': 'Implementation: SECURE_CONTENT_TYPE_NOSNIFF = True',
        'implementacion_session_cookie_secure_csrf_cookie_secure_condicional_a_https': 'Implementation: SESSION_COOKIE_SECURE + CSRF_COOKIE_SECURE conditional on HTTPS',
        'implementacion_x_frame_options_deny': 'Implementation: X_FRAME_OPTIONS = \'DENY\'',
        'infraestructura': 'Infrastructure',
        'lenguaje_principal_del_backend': 'Main backend language.',
        'mantenimiento': 'Maintenance',
        'modelos': 'Models',
        'modelos_y_relaciones': 'Models and Relationships',
        'monitoreo_de_seguridad': 'Security Monitoring',
        'procesamiento_imagenes': 'Image processing.',
        'proteccion_fuerza_bruta': 'Brute force protection.',
        'proteccion_sqli_xss_en_bd': 'SQLi / XSS Protection in DB',
        'rbac_control_de_acceso_por_roles': 'RBAC (Role-Based Access Control)',
        'respaldar_restaurar': 'Backup / Restore',
        'reverse_proxy_ssl_estaticos': 'Reverse proxy, SSL, statics.',
        'secret_key': 'Secret Key',
        'seguridad': 'Security',
        'sirve_archivos_estaticos': 'Serves static files.',
        'sistema_de_plantillas_nativo': 'Native template system.',
        'stack_tecnologico': 'Tech Stack',
        'tecnologias': 'Technologies',
        'tecnologias_arquitectura_y_guia_para_desarrolladores': 'Technologies, architecture and developer guide.',
        'tests': 'Testing',
        'validacion_de_input_telefono_mac': 'Input Validation (phone, MAC)',
        'variables_de_entorno_env': 'Environment variables (.env)',
        'wsgi_server_para_produccion': 'WSGI production server.',
        'xss_crosssite_scripting': 'XSS (Cross-Site Scripting)',
        'resetear_tiempo_sesion': 'Reset session time',
        'tiempo_reiniciado': 'Session time reset!',
    },
}


def theme_context(request):
    ctx = {
        'theme_primary': '#2563eb',
        'theme_secondary': '#1d4ed8',
        'theme_bg': '#f1f5f9',
        'theme_text': '#1e293b',
        'theme_card_bg': '#ffffff',
        'theme_sidebar_bg': '#111827',
        'theme_radius': '0.5rem',
        'theme_custom_css': '',
        'theme_pixel_bg': 'none',
        'theme_text_border_color': '',
        'theme_text_border_width': '0',
        'theme_text_bold': 'false',
        'theme_text_italic': 'false',
        'theme_text_underline': 'false',
        'theme_text_strikethrough': 'false',
        'session_timeout_minutes': 60,
    }
    if request.user.is_authenticated:
        try:
            theme = request.user.theme
            ctx.update({
                'theme_primary': theme.primary_color,
                'theme_secondary': theme.secondary_color,
                'theme_bg': theme.bg_color,
                'theme_text': theme.text_color,
                'theme_card_bg': theme.card_bg,
                'theme_sidebar_bg': theme.sidebar_bg,
                'theme_radius': '9999px' if theme.button_style == 'pill' else ('0.125rem' if theme.button_style == 'square' else '0.5rem'),
                'theme_custom_css': theme.custom_css or '',
                'theme_pixel_bg': theme.pixel_bg or 'none',
                'theme_text_border_color': theme.text_border_color or '',
                'theme_text_border_width': str(theme.text_border_width or '0'),
                'theme_text_bold': 'true' if theme.text_bold else 'false',
                'theme_text_italic': 'true' if theme.text_italic else 'false',
                'theme_text_underline': 'true' if theme.text_underline else 'false',
                'theme_text_strikethrough': 'true' if theme.text_strikethrough else 'false',
            })
        except ThemeSettings.DoesNotExist:
            pass
        try:
            cfg = SessionConfig.get_config()
            ctx['session_timeout_minutes'] = cfg.timeout_minutes
        except Exception:
            pass

    lang = getattr(request, 'session', None) and request.session.get('django_language', None) or 'es'
    if lang not in _TRANSLATIONS:
        lang = 'es'
    ctx['LANG'] = lang
    ctx['LANGUAGE_CODE'] = lang
    ctx['tr'] = _TRANSLATIONS[lang]

    return ctx
