from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/', views.profile_view, name='profile'),
    path('perfil/cambiar-password/', views.change_password_view, name='change_password'),
    path('tema/', views.theme_view, name='theme'),
    path('galeria-fotos/', views.photo_gallery_view, name='photo_gallery'),
    path('actividad/', views.activity_logs_view, name='activity_logs'),
    path('actividad/eliminar/', views.activity_log_delete, name='activity_log_bulk_delete'),
    path('actividad/<int:pk>/eliminar/', views.activity_log_delete, name='activity_log_delete'),
    path('documentacion/', views.documentation_view, name='documentation'),
    path('error-page-settings/', views.error_page_settings_view, name='error_page_settings'),
    path('error-page-settings/preview/', views.error_page_preview, name='error_page_preview'),
    path('error-page-500-settings/', views.error_page_500_settings_view, name='error_page_500_settings'),
    path('error-page-500-settings/preview/', views.error_page_500_preview, name='error_page_500_preview'),
    path('session-config/', views.session_config_view, name='session_config'),
    path('landing-page-config/', views.landing_page_config_view, name='landing_page_config'),
    path('extend-session/', views.extend_session, name='extend_session'),
    path('usuarios/', views.user_list_view, name='user_list'),
    path('tareas/', views.todo_list, name='todo_list'),
    path('tareas/nueva/', views.todo_create, name='todo_create'),
    path('tareas/<int:pk>/toggle/', views.todo_toggle, name='todo_toggle'),
    path('tareas/<int:pk>/eliminar/', views.todo_delete, name='todo_delete'),
    path('set-language/', views.set_language_view, name='set_language'),
    path('whatsapp/', views.whatsapp_config_view, name='whatsapp_config'),
    path('whatsapp/qr/', views.whatsapp_qr_view, name='whatsapp_qr'),
    path('whatsapp/status/', views.whatsapp_status_view, name='whatsapp_status'),
    path('whatsapp/logout/', views.whatsapp_logout_view, name='whatsapp_logout'),
    path('plantillas-recordatorio/', views.recordatorio_template_list, name='recordatorio_template_list'),
    path('plantillas-recordatorio/crear/', views.recordatorio_template_create, name='recordatorio_template_create'),
    path('plantillas-recordatorio/<int:pk>/editar/', views.recordatorio_template_edit, name='recordatorio_template_edit'),
    path('plantillas-recordatorio/<int:pk>/eliminar/', views.recordatorio_template_delete, name='recordatorio_template_delete'),
    path('enviar-recordatorio/', views.enviar_recordatorio_view, name='enviar_recordatorio'),
    path('reportar-error/', views.error_report_view, name='error_report'),
    path('reportes-error/', views.error_report_list_view, name='error_report_list'),
]
